import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";

const config: Config = {
  content: ["./src/**/*.{html,js,svelte,ts}"],
  theme: {
    extend: {
      colors: {
        ink: {
          DEFAULT: "var(--ink)",
          soft: "var(--ink-soft)",
        },
        paper: "var(--paper)",
        surface: "var(--surface)",
        muted: "var(--muted)",
        line: "var(--line)",
        accent: {
          DEFAULT: "var(--accent)",
          ink: "var(--accent-ink)",
          soft: "var(--accent-soft)",
        },
        green: {
          50: "hsl(var(--color-primary-50) / <alpha-value>)",
          100: "hsl(var(--color-primary-100) / <alpha-value>)",
          200: "hsl(var(--color-primary-200) / <alpha-value>)",
          300: "hsl(var(--color-primary-300) / <alpha-value>)",
          400: "hsl(var(--color-primary-400) / <alpha-value>)",
          500: "hsl(var(--color-primary-500) / <alpha-value>)",
          600: "hsl(var(--color-primary-600) / <alpha-value>)",
          700: "hsl(var(--color-primary-700) / <alpha-value>)",
          800: "hsl(var(--color-primary-800) / <alpha-value>)",
          900: "hsl(var(--color-primary-900) / <alpha-value>)",
          950: "hsl(var(--color-primary-950) / <alpha-value>)",
        },
        primary: {
          50: "hsl(var(--color-primary-50) / <alpha-value>)",
          100: "hsl(var(--color-primary-100) / <alpha-value>)",
          200: "hsl(var(--color-primary-200) / <alpha-value>)",
          300: "hsl(var(--color-primary-300) / <alpha-value>)",
          400: "hsl(var(--color-primary-400) / <alpha-value>)",
          500: "hsl(var(--color-primary-500) / <alpha-value>)",
          600: "hsl(var(--color-primary-600) / <alpha-value>)",
          700: "hsl(var(--color-primary-700) / <alpha-value>)",
          800: "hsl(var(--color-primary-800) / <alpha-value>)",
          900: "hsl(var(--color-primary-900) / <alpha-value>)",
          950: "hsl(var(--color-primary-950) / <alpha-value>)",
          DEFAULT: "hsl(var(--color-primary-600) / <alpha-value>)",
        },
        slate: {
          50: "hsl(var(--color-slate-50) / <alpha-value>)",
          100: "hsl(var(--color-slate-100) / <alpha-value>)",
          200: "hsl(var(--color-slate-200) / <alpha-value>)",
          300: "hsl(var(--color-slate-300) / <alpha-value>)",
          400: "hsl(var(--color-slate-400) / <alpha-value>)",
          500: "hsl(var(--color-slate-500) / <alpha-value>)",
          600: "hsl(var(--color-slate-600) / <alpha-value>)",
          700: "hsl(var(--color-slate-700) / <alpha-value>)",
          800: "hsl(var(--color-slate-800) / <alpha-value>)",
          900: "hsl(var(--color-slate-900) / <alpha-value>)",
        },
        success: {
          50: "hsl(var(--color-success-50) / <alpha-value>)",
          100: "hsl(var(--color-success-100) / <alpha-value>)",
          200: "hsl(var(--color-success-200) / <alpha-value>)",
          500: "hsl(var(--color-success-500) / <alpha-value>)",
          600: "hsl(var(--color-success-600) / <alpha-value>)",
          700: "hsl(var(--color-success-700) / <alpha-value>)",
          DEFAULT: "hsl(var(--color-success) / <alpha-value>)",
        },
        warning: {
          50: "hsl(var(--color-warning-50) / <alpha-value>)",
          100: "hsl(var(--color-warning-100) / <alpha-value>)",
          200: "hsl(var(--color-warning-200) / <alpha-value>)",
          500: "hsl(var(--color-warning-500) / <alpha-value>)",
          600: "hsl(var(--color-warning-600) / <alpha-value>)",
          700: "hsl(var(--color-warning-700) / <alpha-value>)",
          DEFAULT: "hsl(var(--color-warning) / <alpha-value>)",
        },
        error: {
          50: "hsl(var(--color-error-50) / <alpha-value>)",
          100: "hsl(var(--color-error-100) / <alpha-value>)",
          200: "hsl(var(--color-error-200) / <alpha-value>)",
          500: "hsl(var(--color-error-500) / <alpha-value>)",
          600: "hsl(var(--color-error-600) / <alpha-value>)",
          700: "hsl(var(--color-error-700) / <alpha-value>)",
          DEFAULT: "hsl(var(--color-error) / <alpha-value>)",
        },
        info: {
          50: "hsl(var(--color-info-50) / <alpha-value>)",
          100: "hsl(var(--color-info-100) / <alpha-value>)",
          200: "hsl(var(--color-info-200) / <alpha-value>)",
          500: "hsl(var(--color-info-500) / <alpha-value>)",
          600: "hsl(var(--color-info-600) / <alpha-value>)",
          700: "hsl(var(--color-info-700) / <alpha-value>)",
          DEFAULT: "hsl(var(--color-info) / <alpha-value>)",
        },
      },
      fontFamily: {
        serif: ["'Fraunces'", "'Source Serif 4'", "Georgia", "serif"],
        display: ["'Fraunces'", "'Source Serif 4'", "Georgia", "serif"],
        sans: [
          "'Inter Tight'",
          "-apple-system",
          "BlinkMacSystemFont",
          "'Segoe UI'",
          "sans-serif",
        ],
        mono: ["'JetBrains Mono'", "ui-monospace", "monospace"],
      },
      fontSize: {
        xs: ["0.75rem", { lineHeight: "1rem" }],
        sm: ["0.875rem", { lineHeight: "1.25rem" }],
        base: ["0.9375rem", { lineHeight: "1.5rem" }],
        lg: ["1rem", { lineHeight: "1.5rem" }],
        xl: ["1.125rem", { lineHeight: "1.75rem" }],
        "2xl": ["1.375rem", { lineHeight: "1.875rem" }],
        "3xl": ["1.75rem", { lineHeight: "2.25rem" }],
        "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
        "5xl": ["2.75rem", { lineHeight: "3rem" }],
      },
      boxShadow: {
        sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
        DEFAULT:
          "0 2px 8px 0 rgba(0, 0, 0, 0.08), 0 1px 3px 0 rgba(0, 0, 0, 0.06)",
        md: "0 4px 12px 0 rgba(0, 0, 0, 0.1), 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
        lg: "0 8px 20px 0 rgba(0, 0, 0, 0.12), 0 4px 8px 0 rgba(0, 0, 0, 0.08)",
        xl: "0 16px 32px 0 rgba(0, 0, 0, 0.15), 0 8px 16px 0 rgba(0, 0, 0, 0.1)",
      },
      borderRadius: {
        DEFAULT: "0.625rem",
        sm: "0.375rem",
        md: "0.625rem",
        lg: "0.875rem",
        xl: "1.25rem",
      },
      animation: {
        "fade-in": "fadeIn 300ms ease-in-out forwards",
        "slide-up": "slideUp 400ms ease-out forwards",
        "slide-in-right": "slideInRight 300ms ease-out forwards",
        "scale-in": "scaleIn 200ms ease-out forwards",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(16px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        slideInRight: {
          "0%": { transform: "translateX(-16px)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        scaleIn: {
          "0%": { transform: "scale(0.95)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
      },
    },
  },
  plugins: [forms],
};

export default config;
